export const FETCH_REVIEW_WORD = "account/FETCH_REVIEW_WORD";
export const UPDATE_STATUS_GAME_1_ACTION = "account/UPDATE_STATUS_GAME_1_ACTION";
export const UPDATE_STATUS_SHOW_GAME = "account/UPDATE_STATUS_SHOW_GAME";
export const UPDATE_STATUS_GAME_2_ACTION = "account/UPDATE_STATUS_GAME_2_ACTION";
export const UPDATE_STATUS_GAME_3_ACTION = "account/UPDATE_STATUS_GAME_3_ACTION";
export const UPDATE_STATUS_GAME_4_ACTION = "account/UPDATE_STATUS_GAME_4_ACTION";
export const UPDATE_LIST_REVIEW = "account/UPDATE_LIST_REVIEW";
export const UPDATE_STATE = "account/UPDATE_STATE";
export const RESET_GAME = "account/RESET_GAME";

