const en = {
  general: {
    remindReview: "Review at Golden Time to maximize your memorization efficiency",
    memorize1000Month: "Memorize 1000 words in 1 month",
    getStarted: "Get started",
    haveAcc: "I already have an account",
    courses: "Courses",
    coursesList: "COURSE LIST",
    lessionList: "Lesson List",
    askGoldenTime:
      "Mochi would like to send you notification of the Golden Time",
    allowNotification: "Allow notification",
    learn3Free:
      "You've learned 3 free trial lessons, please update to premium to unlock all lessons",
    chooseLang: "Choose a display language",
    joinMemberGroup: "Join Mochi Facebook Group",
    chatMochi: "Chat with Mochi",
    FAQ: "FAQ",
    activeDate: "Active date",
    expireDate: "Expiration date",
    enterNewName: "Enter your new display name",
    saveChange: "Save changes",
    cancel: "Cancel",
    startTrial: "Start your trial lessons",
    noWord: "You do not have any words to review.",
    needLearn: "Let's learn a new lesson",
    changeList: "You've just changed your review word list",
    accExpireSoon: "Your course will expire in {x} days. Please extend",
    extendNow: "Extend now",
    accExpired: "Your account has expired. Please expend.",
    loginToAddCode: "Log in to enter your card code",
    joinGroup: "Join Mochi Facebook group",
    joinNow: "Join now",
    fail: "Fail",
    distinguish: "Distinguish between 0 and O",
    checkNetwork: "Check your Internet connection to update the Golden Time",
    reconnect: "Reconnect",
    review: "Review",
    learn: "Learn new words",
    notebook: "Notebook",
    community: "Community",
    youAnswerCorrect: "You answered",
    sentences: "sentences correctly",
    wonderful: "Wonderful!",
    continueLearn: "Continue learning to grow your tree!",
    upgradeLevel: "Upgrade your level of Notebook",
    youNeed: "You need",
    wordToOpen: "You need {x} words to open new title",
    levelMemory: "Your level of Memory is",
    seeAtGT: "See you later at ",
    updateGT: "Updating",
    goldenTime: "'Golden Time'",
    guestAcc: "Guest account",
    premiumAcc: "Premium account",
    freeAcc: "Free account",

    highLightWord: "Highlight the word you want to translate ",
    knownFunction: "I've already known this function",
    save: "Save",
    saved: "Saved",
    youJustLearned: "You've just learned",
    wordsToUpgrade: "You need {x} words to upgrade your level of Notebook",
    dontRememberWord: "I don't remember this word",
    relax: "Relax for a while",
    letContinue: "Let's continue",
    goPremium: "Go premium to unlock all lessons",
    upgradeNow: "Upgrade now",
    uploadMess: "Upload image no larger than 1MB",
    nameMess: "User name from 3 - 15 characters",
    gotIt: "Got it!",
    check: "Check",
    startNow: "Start now",
    exitSure: "Are you sure to exit?",
    continueReview: "Continue review",
    willExpire: "Your course will expire in {x} days. Please extend",
    courseHasExpire: "Your course has expired. Please extend.",
    vietnamese: "Vietnamese",
    english: "English",
  },
  other: {
    keepGoing: "Keep going!",
    youCan: "You can do it!",
    wordAlreadyKnow: "I've already known this word",
    memorize1000: "Memorize 1000 words in 1 month",
    check: "Check",
    FAQ: "FAQ",
  },
  info: {
    loginToStudy: "Log in to study",
    createAccNow: "Create a new account",
    login: "Login",
    unlockNow: "Unlock now",
    translate: "Translate",
    messageLogin: "Log in to study with Mochi",
    logOut: "Log out",
    howCreateAcc: "How do you want to create an account",
    google: "Continue with G+",
    facebook: "Continue with Facebook",
    apple: "Continue with Apple",
    createWithEmail: "Create your own account with an email",
    or: "or",
    createMochiAcc: "Create a Mochi account",
    yourName: "Your name",
    exactEmail: "Enter your email precisely",
    createPass: "Create password",
    createAcc: "Create an account",
    haveAccAlready: "You have an account already?",
    show: "Show",
    hide: "Hide",
    inboxMochi: "Inbox Mochi",
    createAccSuccess:
      "You've successfully created an account and unlocked free trial lessons",
    loginSuccess: "You have successfully logged in!",
    enterEmail: "Enter your account email",
    password: "Password",
    enterPass: "Enter your account password",
    exactPass: "Enter your password precisely",
    forgotPass: "Forgot password?",
    createNewAcc: "Create a new account",

    dontHaveAcc: "Don't have an account yet",
    thankyou: "Thank you for informing Mochi <3",
    enterQuestion: "Enter your question here",
    inboxChangePass: "Please inbox Mochi if you want to change your password",
    emailNotCorrect: "Email is not in the correct format",
    emailNotExist: "Email does not exist",
    emailNotFormat: "Email is not in the correct format. Please check again.",
    passwordAtLeast: "Password must have at least 6 characters",
    passwordIncorrect: "The password is incorrect. Try again.",
  },
  dashboard: {
    level1: "Level 1",
    level2: "Level 2",
    level3: "Level 3",
    level4: "Level 4",
    level5: "Level 5",
    searchWord: "Search a word",
    noWord: "Oops, no words at this level",
    notFound: "MochiMochi cannot find this word in your list, try again.",
    words: "words",
    wordToReview: "Words to review next",
    reviewNow: "Review now",
    activeGoldenTime: 'To activate your "Golden Time", learn a new lesson.',
    learnNewWord: "Learn new words",
    learnContinuously: "You've learned continuously for",
    days: "days",
    youLearned: "You've learned",
    achievements: "Achievements",
    accSetting: "Account setting",
    turnOnGoldenTime: "Turn on notice of the Golden Time",
    enterCode: "Enter card code",
    enterMochiCode: "Enter your card code",
    enterYourCode: "Enter card code",
    activeCode: "Activate card code",
    activeSuccess: "You've successfully activated card code",
  },
  learn: {
    typingKanji: "Type the pronunciation of Kanji",
    levelNotebook: "Level of Notebook",
    levelMemo: "Level of Memory",
    learnHard: "You have learned continously for",
    continueDays: "days",
    keepGoing: "Keep going!",
    continue: "Continue",
    report: "Report content errors",
    listenAndWrite: "Listen and write down",
    writeWordHear: "Write the word you hear",
    fillBlank: "Fill in the blank",
    finishLesson: "Finish your lesson, or you will loose all learning process",
    continueLearn: "Continue learning",
    exit: "Exit",
    describeProblemPlease:
      "Please describe your problems in details so that Mochi can help you faster",
    senMochi: "Send to Mochi",
    cancel: "Cancel",
    describeDetail: "Describe your problem in details",

    startLearn: "Start learning",
    chooseMeaning: "Choose a meaning for the underlined word",
    chooseWord: "Choose a word to fill in the blank",
    reviewAtGoldenTime:
      "Review at Golden Time to maximize your memorization efficiency",
    learnMore: "Learn more",
    chooseCorrect: "Choose the correct answer",
    arrange: "Arrange word from letters",
    selectSave: "Select words you want cho save to Notebook",
  },
};
//en
export default en;
