const vi = {
  general: {
    remindReview: "Ôn tập vào đúng Thời Điểm Vàng giúp bạn tăng 10 lần khả năng ghi nhớ",
    memorize1000Month: "Ghi nhớ 1000 từ vựng trong 1 tháng",
    getStarted: "Bắt đầu ngay",
    haveAcc: "Mình đã có tài khoản",
    courses: "CÁC KHOÁ HỌC",
    coursesList: "DANH SÁCH CÁC KHOÁ HỌC",
    lessionList: "Danh sách bài học",
    askGoldenTime: "Bạn có muốn nhận thông báo  “Thời điểm vàng” không?",
    allowNotification: "Bật thông báo",
    learn3Free:
      "Bạn đã học hết 3 bài học thử, đăng kí để mở khoá toàn bộ các khoá học nhé",
    chooseLang: "Chọn ngôn ngữ hiển thị",
    joinMemberGroup: "Tham gia group học viên",
    chatMochi: "Chat với Mochi",
    FAQ: "Tham khảo những câu hỏi thường gặp",
    activeDate: "Ngày kích hoạt",
    expireDate: "Ngày hết hạn",
    enterNewName: "Nhập tên hiển thị mới",
    saveChange: "Lưu thay đổi",
    cancel: "Huỷ",

    startTrial: "Học thử ngay",
    noWord: "Bạn chưa có từ vựng nào trong sổ tay.",
    needLearn: "Hãy học 1 bài từ mới để cập nhật sổ tay",
    changeList: "Bạn vừa thay đổi danh sách từ cần ôn tập",
    accExpireSoon:
      "Khoá học của bạn sẽ hết hạn sau {x} ngày nữa. Gia hạn để tiếp tục học cùng Mochi nhé!",
    extendNow: "Gia hạn ngay",
    accExpired:
      "Khoá học của bạn đã hết hạn. Vui lòng gia hạn để tiếp tục học cùng Mochi nhé!",
    loginToAddCode: "Đăng nhập để nạp mã thẻ học ngay bạn nhé",
    joinGroup: "Tham gia thảo luận tại group học tiếng Nhật của Mochi",
    joinNow: "Tham gia ngay",
    fail: "Không thành công",
    distinguish: "Phân biệt số 0 và chữ O bạn nhé",
    checkNetwork:
      "Vui lòng kiểm tra lại kết nối mạng để cập nhật đầy đủ dữ liệu ôn tập nhé",
    reconnect: "Cập nhật lại",
    review: "Ôn tập",
    learn: "Học từ mới",
    notebook: "Sổ tay",
    community: "Cộng đồng",
    youAnswerCorrect: "Bạn đã trả lời đúng",
    sentences: "câu",
    wonderful: "Tuyệt vời",
    continueLearn: "Tiếp tục học để cây xanh tươi nhé",
    upgradeLevel: " Nâng cấp sổ tay cấp độ",
    youNeed: "Cần thêm",
    wordToOpen: "Cần thêm {x} từ để mở danh hiệu mới",
    levelMemory: "Bạn đã trở thành siêu trí nhớ cấp",
    seeAtGT: "Hẹn gặp lại bạn vào ",
    updateGT: "Đang cập nhật",
    goldenTime: "'Thời Điểm Vàng'",
    guestAcc: "Guest account",
    premiumAcc: "Premium account",
    freeAcc: "Free account",

    highLightWord: "Hãy bôi đen từ bạn muốn dịch để Mochi tra cứu giúp bạn nhé",
    knownFunction: "Tôi đã biết chức năng này",
    save: "Lưu từ",
    saved: "Đã lưu",
    youJustLearned: "Bạn vừa nạp thêm",
    wordsToUpgrade: "Cần thêm {x} từ để nâng cấp sổ tay",
    dontRememberWord: "Tôi không nhớ từ này",
    relax: "Thư giãn chút rồi học tiếp nha",
    letContinue: "Học tiếp thôi",
    goPremium: "Nâng cấp tài khoản để mở khoá tất cả các khoá học",
    upgradeNow: "Nâng cấp ngay",
    uploadMess: "Hình ảnh không được quá 1MB",
    nameMess: "Tên hiển thị phải từ 3 - 15 ký tự",
    gotIt: "Mình hiểu rồi",
    check: "Kiểm tra",
    startNow: "Bắt đầu ngay",
    exitSure: "Bạn có chắc chắn muốn thoát",
    continueReview: "Ôn tập tiếp",
    willExpire:
      "Khoá học của bạn sẽ hết hạn sau {x} ngày nữa. Gia hạn để tiếp tục học cùng Mochi nhé!",
    courseHasExpire:
      "Khoá học của bạn đã hết hạn. Vui lòng gia hạn để tiếp tục học cùng Mochi nhé!",
    vietnamese: "Tiếng Việt",
    english: "Tiếng Anh",
  },
  other: {
    keepGoing: "Cố gắng thêm chút nhé",
    youCan: "Cố lên, bạn có thể làm được mà",
    wordAlreadyKnow: "Mình đã thuộc từ này",
    memorize1000: "Ghi nhớ 1000 từ vựng trong 1 tháng",
    check: "Kiểm tra",
    FAQ: "Câu hỏi thường gặp",
  },
  info: {
    loginToStudy: "Đăng nhập để học ngay nhé",
    createAccNow: "Tạo tài khoản ngay",
    login: "Đăng nhập",
    unlockNow: "Mở khoá ngay",
    translate: "Dịch",
    messageLogin: "Đăng nhập để trải nghiệm học tập cùng Mochi bạn nhé",
    logOut: "Đăng xuất",
    howCreateAcc: "Bạn muốn tạo tài khoản bằng cách nào nhỉ",
    google: "Tiếp tục với G+",
    facebook: "Tiếp tục với Facebook",
    apple: "Tiếp tục với Apple",
    createWithEmail: "Tự tạo tài khoản với email",
    or: "HOẶC",
    createMochiAcc: "Cùng tạo 1 tài khoản Mochi nào",
    yourName: "Tên của bạn",
    exactEmail: "Nhập chính xác email của bạn",
    createPass: "Tạo mật khẩu (dễ nhớ chút nhé ^^)",
    createAcc: "Tạo tài khoản",
    haveAccAlready: "Bạn đã có tài khoản?",
    show: "Hiển thị",
    hide: "Ẩn",
    inboxMochi: "Inbox cho Mochi",
    createAccSuccess:
      "Bạn đã tạo tài khoản thành công và được mở khoá tất cả các bài học thử",
    loginSuccess: "Bạn đã đăng nhập thành công tài khoản học MochiMochi",
    enterEmail: "Nhập email tài khoản học",
    password: "Mật khẩu",
    enterPass: "Nhập mật khẩu tài khoản học",
    exactPass: "Nhập chính xác mật khẩu của bạn",
    forgotPass: "Quên mật khẩu?",
    createNewAcc: "Tạo tài khoản học mới",

    dontHaveAcc: "Chưa có tài khoản",
    thankyou: "Cảm ơn bạn đã báo cho Mochi nha <3",
    enterQuestion: "Nhập câu hỏi của bạn tại đây",
    inboxChangePass: "Bạn hãy inbox cho Mochi để được hỗ trợ đổi mật khẩu nhé",
    emailNotCorrect: "Email không đúng định dạng",
    emailNotExist: "Email không tồn tại",
    emailNotFormat: "Email sai định dạng, bạn kiểm tra lại nhé",
    passwordAtLeast: "Mật khẩu phải từ 6 ký tự",
    passwordIncorrect: "Mật khẩu chưa chính xác, bạn kiểm tra lại nhé",
  },
  dashboard: {
    level1: "Cấp độ 1",
    level2: "Cấp độ 2",
    level3: "Cấp độ 3",
    level4: "Cấp độ 4",
    level5: "Cấp độ 5",
    searchWord: "Gõ vào đây từ bạn muốn tìm",
    noWord: "Ú, không có từ vựng nào của bạn đang ở cấp độ này bạn ơi.",
    notFound:
      "Mochi không tìm được từ này trong danh sách từ đã ôn của bạn. Bạn thử tìm từ khác nha.",
    words: "từ",
    wordToReview: "Chuẩn bị ôn tập",
    reviewNow: "Ôn tập ngay",
    activeGoldenTime:
      'Để kích hoạt tính năng "Thời điểm vàng" hãy học 1 bài học từ mới',
    learnNewWord: "Học từ mới",
    learnContinuously: "Bạn đã học liên tục",
    days: "ngày",
    youLearned: "Bạn đã học được",
    achievements: "Thành tích học tập",
    accSetting: "Cài đặt tài khoản",
    turnOnGoldenTime: "Bật thông báo thời điểm vàng ngay",
    enterCode: "Nạp mã thẻ học",
    enterMochiCode: "Nạp mã thẻ học nhận được từ Mochi",
    enterYourCode: "Nhập mã thẻ học của bạn",
    activeCode: "Kích hoạt mã",
    activeSuccess: "Bạn đã kích hoạt mã thành công,vào học cùng Mochi ngay nhé",
  },
  learn: {
    typingKanji: "Gõ cách đọc của từ Kanji",
    levelNotebook: "SỔ TAY CẤP ĐỘ",
    levelMemo: "SIÊU TRÍ NHỚ CẤP ĐỘ",
    learnHard: "BẠN ĐÃ HỌC CHĂM CHỈ",
    continueDays: "ngày liên tiếp",
    keepGoing: "Cố lên, cố lên!",
    continue: "Tiếp tục",
    report: "Báo lỗi nội dung",
    listenAndWrite: "Nghe và viết lại",
    writeWordHear: "Gõ lại từ bạn đã nghe được",
    fillBlank: "Điền từ",
    finishLesson:
      "Làm nốt bài đi. Thoát bây giờ là toàn bộ kết quả học không được lưu lại đó.",
    continueLearn: "Ở lại học tiếp",
    exit: "Thoát",
    describeProblemPlease:
      "Hãy mô tả chi tiết vấn đề bạn đang gặp để Mochi có thể nhanh chóng kiểm tra và khắc phục nhé",
    senMochi: "Gửi cho Mochi",
    cancel: "Huỷ",
    describeDetail: "Mô tả chi tiết vấn đề bạn đang gặp",

    startLearn: "Học ngay",
    chooseMeaning: "Chọn nghĩa của từ được gạch chân",
    chooseWord: "Chọn từ điền vào chỗ trống",
    reviewAtGoldenTime:
      "Ôn tập vào đúng thời điểm vàng sẽ giúp bạn tăng hiệu quả ghi nhớ",
    learnMore: "Tìm hiểu thêm",
    chooseCorrect: "Chọn đáp án đúng",
    arrange: "Sắp xếp các ký tự thành từ đúng",
    selectSave: "Chọn từ vựng bạn muốn lưu vào sổ tay",
  },
};
//en
export default vi;
